'use client'
import { useEffect, useRef, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import type { Game } from '../../lib/types'
import { positionsForCrew } from '../components/CrewSizeControls'
import { DAY_NAMES, DAY_COUNT, migrateLegacyDayStorage, readTournament, saveTournament, type Tournament } from '../../lib/tournament'

type CrewSize = 2 | 3 | 4
const DEFAULT_DATE='2026-08-30'
const blankGame=(number=1):Game=>({id:`game-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,number,date:DEFAULT_DATE,start:'09:00',field:'Diamond 1',teams:'',division:'',positions:positionsForCrew(2)})
const read=<T,>(key:string,f:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'null')??f}catch{return f}}
function parseCSV(text:string):string[][]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell.trim());cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());cell='';if(row.some(v=>v))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell.trim());if(row.some(v=>v))rows.push(row)}return rows}
const normalise=(v:string)=>v.replace(/^\ufeff/,'').trim().toLowerCase().replace(/\s+/g,' ')
const column=(row:string[],headers:string[],names:string[])=>{const i=headers.findIndex(h=>names.map(normalise).includes(h));return i>=0?(row[i]||'').trim():''}
const crewDescription=(n:number)=>n===3?'Plate + 1st Base + 3rd Base':n===4?'Plate + 1st Base + 2nd Base + 3rd Base':'Plate + 1st Base'

export default function MultiDaySchedule(){
 const [mounted,setMounted]=useState(false),[tournament,setTournament]=useState<Tournament|null>(null),[dayIndex,setDayIndex]=useState(0),[games,setGames]=useState<Game[]>([]),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState<Game>(blankGame()),[message,setMessage]=useState('')
 const fileInput=useRef<HTMLInputElement>(null)
 useEffect(()=>{migrateLegacyDayStorage();const t=readTournament(read<Game[]>('softball-games',[]),read('softball-assignments',[]),read('softball-manual-locks',[]));const selected=Math.max(0,Math.min(DAY_COUNT-1,Number(localStorage.getItem('softball-selected-day')||0)));setTournament(t);setDayIndex(selected);setGames(t.days[selected].games);setMounted(true)},[])
 const saveCurrent=(gs=games,index=dayIndex)=>{if(!tournament)return;const next={...tournament,days:tournament.days.map((d,i)=>i===index?{...d,games:gs,date:gs[0]?.date||d.date}:d)};setTournament(next);saveTournament(next);localStorage.setItem('softball-games',JSON.stringify(gs))}
 const switchDay=(index:number)=>{if(!tournament||index===dayIndex)return;saveCurrent();const d=tournament.days[index];setDayIndex(index);setGames(d.games);setEditingId(null);setForm(blankGame((d.games.length?Math.max(...d.games.map(g=>g.number))+1:1)));localStorage.setItem('softball-selected-day',String(index));localStorage.setItem('softball-games',JSON.stringify(d.games));setMessage(`${DAY_NAMES[index]} selected.`)}
 const resetForm=()=>{setForm(blankGame(games.length?Math.max(...games.map(g=>g.number))+1:1));setEditingId(null)}
 const saveGame=(e:FormEvent)=>{e.preventDefault();if(!form.teams.trim()||!form.field.trim()||!form.start){setMessage('Please enter Team 1, Team 2, time and diamond.');return}const next=editingId?games.map(g=>g.id===editingId?form:g):[...games,form].sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.number-b.number);setGames(next);saveCurrent(next);setMessage(`Game ${form.number} ${editingId?'updated':'added'}.`);resetForm()}
 const editGame=(g:Game)=>{setEditingId(g.id);setForm({...g});setMessage(`Editing Game ${g.number}.`)}
 const deleteGame=(id:string)=>{const g=games.find(x=>x.id===id);if(!g||!confirm(`Delete Game ${g.number}? Existing appointments for this game will also be removed.`))return;const next=games.filter(x=>x.id!==id);setGames(next);saveCurrent(next);const assignments=read<any[]>('softball-assignments',[]).filter(a=>a.gameId!==id);localStorage.setItem('softball-assignments',JSON.stringify(assignments));setMessage(`Game ${g.number} deleted.`)}
 const setCrew=(size:CrewSize)=>setForm(g=>({...g,positions:positionsForCrew(size)}))
 const uploadCSV=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const rows=parseCSV(String(r.result||''));if(rows.length<2){setMessage('CSV is empty or has no game rows.');return}const headers=rows[0].map(normalise),imported:Game[]=[],skipped:string[]=[];rows.slice(1).forEach((row,i)=>{const team1=column(row,headers,['team 1','team1','home team']),team2=column(row,headers,['team 2','team2','away team']),time=column(row,headers,['time','start','start time']),diamond=column(row,headers,['diamond','field']);if(!team1||!team2||!time||!diamond){skipped.push(`Row ${i+2}`);return}const requested=Number(column(row,headers,['crew size','crew','umpires','crew members'])),crew:CrewSize=requested===3?3:requested===4?4:2;imported.push({id:`import-${Date.now()}-${i}-${Math.random().toString(36).slice(2,7)}`,number:Number(column(row,headers,['game','game number','game #']))||i+1,date:column(row,headers,['date'])||DEFAULT_DATE,start:time,field:diamond,teams:`${team1} vs ${team2}`,division:column(row,headers,['division','competition']),positions:positionsForCrew(crew)})});if(!imported.length){setMessage('No games uploaded. Required columns are Team 1, Team 2, Time and Diamond.');return}setGames(imported);setEditingId(null);saveCurrent(imported);setMessage(`${imported.length} games uploaded${skipped.length?`; ${skipped.length} skipped`:''}.`)}catch{setMessage('Could not read that CSV. Please check the file format.')}finally{e.target.value=''}};r.readAsText(file)}
 if(!mounted)return <main><div className="loading">Loading schedule…</div></main>
 return <main><header><div><div className="brand">DIAMOND • OFFICIATING</div><h1>Build / Upload Schedule</h1><p>Build the schedule for the selected tournament day.</p></div><a href="/dashboard">← Dashboard</a></header><div className="days"><span>Tournament day</span>{DAY_NAMES.map((n,i)=><button key={n} className={i===dayIndex?'active':''} onClick={()=>switchDay(i)}>{n}</button>)}</div>
 <section className="card"><div className="head"><div><h2>{editingId?`Edit Game ${form.number}`:'Add Game Manually'}</h2><p>End time is not required.</p></div>{editingId&&<button onClick={resetForm}>Cancel edit</button>}</div><form onSubmit={saveGame}><label>Game number<input type="number" min="1" value={form.number} onChange={e=>setForm({...form,number:Number(e.target.value)})}/></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Team 1<input value={form.teams.split(/\s+vs\s+/i)[0]||''} onChange={e=>{const p=form.teams.split(/\s+vs\s+/i);setForm({...form,teams:`${e.target.value} vs ${p[1]||''}`})}}/></label><label>Team 2<input value={form.teams.split(/\s+vs\s+/i)[1]||''} onChange={e=>{const p=form.teams.split(/\s+vs\s+/i);setForm({...form,teams:`${p[0]||''} vs ${e.target.value}`})}}/></label><label>Time<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Diamond<input value={form.field} onChange={e=>setForm({...form,field:e.target.value})}/></label><label>Division<input value={form.division} onChange={e=>setForm({...form,division:e.target.value})}/></label><div className="crew"><b>Crew size</b>{([2,3,4] as const).map(n=><button type="button" key={n} className={form.positions.length===n?'active':''} onClick={()=>setCrew(n)}>{n}</button>)}<small>{crewDescription(form.positions.length)}</small></div>{message&&<div className="message">{message}</div>}<button className="primary" type="submit">{editingId?'Save Game Changes':'+ Add Game'}</button></form></section>
 <section className="card"><div className="head"><div><h2>Upload CSV · {DAY_NAMES[dayIndex]}</h2><p>Team 1, Team 2, Time, Diamond and Crew Size. No end time required.</p></div><button className="upload" onClick={()=>fileInput.current?.click()}>↑ Choose CSV</button><input ref={fileInput} hidden type="file" accept=".csv,text/csv" onChange={uploadCSV}/></div><code>Game, Date, Team 1, Team 2, Time, Diamond, Division, Crew Size</code></section>
 <section className="card"><h2>Current Schedule · {DAY_NAMES[dayIndex]}</h2><p>{games.length} game{games.length===1?'':'s'}.</p><div className="table"><table><thead><tr><th>Game</th><th>Date</th><th>Time</th><th>Diamond</th><th>Teams</th><th>Division</th><th>Crew</th><th>Actions</th></tr></thead><tbody>{games.map(g=><tr key={g.id}><td>#{g.number}</td><td>{g.date}</td><td>{g.start}</td><td>{g.field}</td><td>{g.teams}</td><td>{g.division||'—'}</td><td>{g.positions.length}</td><td><button onClick={()=>editGame(g)}>Edit</button><button className="delete" onClick={()=>deleteGame(g.id)}>Delete</button></td></tr>)}</tbody></table></div>{!games.length&&<div className="empty">No games on this day yet.</div>}</section>
 <style jsx>{`main{min-height:100vh;background:#f5f7f8;color:#1c2b33;font-family:Arial,sans-serif;padding-bottom:60px}.loading{min-height:100vh;display:grid;place-items:center;color:#667983}header{background:#fff;border-bottom:1px solid #dde5e9;padding:24px 5%;display:flex;justify-content:space-between;align-items:center}.brand{font-size:11px;letter-spacing:2px;color:#5d7380}h1{margin:5px 0}p{color:#6d7e86;font-size:13px}header a{color:#1587b2;text-decoration:none;font-weight:600;font-size:13px}.days{margin:12px 5%;display:flex;gap:5px;align-items:center;overflow:auto}.days span{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#71828a;margin-right:5px}.days button,button{border:1px solid #cbd6dc;background:#fff;border-radius:6px;padding:8px 12px;cursor:pointer}.days button.active,.crew button.active,.upload,.primary{background:#1587b2;color:#fff;border-color:#1587b2}.card{margin:20px 5%;background:#fff;border:1px solid #dce4e8;border-radius:8px;padding:22px}.head{display:flex;justify-content:space-between;align-items:center;gap:15px}.head h2{margin:0}.head p{margin-top:5px}form{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:18px}label{font-size:11px;font-weight:700;color:#536771;display:flex;flex-direction:column;gap:6px}input{padding:9px;border:1px solid #cbd6dc;border-radius:5px;font:inherit}.crew{grid-column:1/-1;background:#f7f9fa;padding:13px;display:flex;align-items:center;gap:8px}.crew small{color:#687982;margin-left:5px}.primary{grid-column:1/-1;font-weight:700}.message{grid-column:1/-1;padding:10px;background:#eef7fa;border:1px solid #c7e2ea;color:#356673}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:10px;border-bottom:1px solid #e7ecef;text-align:left;white-space:nowrap}th{background:#f7f9fa;font-size:9px;letter-spacing:1px;color:#667983}td button{padding:6px 9px;margin-right:5px}.delete{color:#a43d35}code{display:block;background:#f7f9fa;padding:10px;border-radius:5px;color:#51636b}.empty{text-align:center;padding:30px;color:#74858d}@media(max-width:800px){form{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){form{grid-template-columns:1fr}.card{margin-left:3%;margin-right:3%}.head{flex-direction:column;align-items:flex-start}}`}</style></main>
}
