'use client'

import { useEffect, useRef, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import { Game } from '../../lib/types'
import { positionsForCrew } from '../components/CrewSizeControls'

const DEFAULT_DATE = '2026-08-30'
type CrewSize = 2 | 3 | 4

const blankGame = (number = 1): Game => ({ id:`game-${Date.now()}-${Math.random().toString(36).slice(2,8)}`, number, date:DEFAULT_DATE, start:'09:00', field:'Diamond 1', teams:'', division:'', positions:positionsForCrew(2) })

function readGames(): Game[] { try { const stored=JSON.parse(localStorage.getItem('softball-games')||'null'); return Array.isArray(stored)?stored:[] } catch { return [] } }

function parseCSV(text:string):string[][] { const rows:string[][]=[]; let row:string[]=[],cell='',quoted=false; for(let i=0;i<text.length;i+=1){const char=text[i]; if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i+=1}else quoted=!quoted;continue} if(char===','&&!quoted){row.push(cell.trim());cell='';continue} if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i+=1;row.push(cell.trim());cell='';if(row.some(value=>value.length>0))rows.push(row);row=[];continue} cell+=char} if(cell.length>0||row.length>0){row.push(cell.trim());if(row.some(value=>value.length>0))rows.push(row)} return rows }
const normalise=(value:string)=>value.replace(/^\ufeff/,'').trim().toLowerCase().replace(/\s+/g,' ')
function column(row:string[],headers:string[],names:string[]):string { const wanted=names.map(normalise); const index=headers.findIndex(header=>wanted.includes(header)); return index>=0?(row[index]||'').trim():'' }
function crewDescription(size:number):string { if(size===3)return 'Plate + 1st Base + 3rd Base'; if(size===4)return 'Plate + 1st Base + 2nd Base + 3rd Base'; return 'Plate + 1st Base' }

export default function SchedulePage(){
 const [games,setGames]=useState<Game[]>([]),[mounted,setMounted]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState<Game>(blankGame()),[message,setMessage]=useState('');const fileInput=useRef<HTMLInputElement>(null)
 useEffect(()=>{setGames(readGames());setMounted(true)},[])
 useEffect(()=>{if(mounted)localStorage.setItem('softball-games',JSON.stringify(games))},[games,mounted])
 function resetForm(){const nextNumber=games.length>0?Math.max(...games.map(game=>game.number))+1:1;setForm(blankGame(nextNumber));setEditingId(null)}
 function saveGame(event:FormEvent<HTMLFormElement>){event.preventDefault();const teams=form.teams.trim();if(!teams||!form.field.trim()||!form.start){setMessage('Please enter Team 1, Team 2, time and diamond.');return}if(editingId){setGames(current=>current.map(game=>game.id===editingId?{...form,teams}:game));setMessage(`Game ${form.number} updated.`)}else{setGames(current=>[...current,{...form,teams}].sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.number-b.number));setMessage(`Game ${form.number} added.`)}resetForm()}
 function editGame(game:Game){setEditingId(game.id);setForm({...game});setMessage(`Editing Game ${game.number}.`);window.scrollTo({top:0,behavior:'smooth'})}
 function deleteGame(id:string){const game=games.find(item=>item.id===id);if(!game||!window.confirm(`Delete Game ${game.number}? Existing umpire appointments for this game will also be removed.`))return;setGames(current=>current.filter(item=>item.id!==id));try{const assignments=JSON.parse(localStorage.getItem('softball-assignments')||'[]');localStorage.setItem('softball-assignments',JSON.stringify(assignments.filter((item:{gameId:string})=>item.gameId!==id)))}catch{}setMessage(`Game ${game.number} deleted.`)}
 function setCrew(size:CrewSize){setForm(current=>({...current,positions:positionsForCrew(size)}))}
 function uploadCSV(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setMessage('Reading CSV…');const reader=new FileReader();reader.onload=()=>{try{const rows=parseCSV(String(reader.result||''));if(rows.length<2){setMessage('CSV is empty or has no game rows.');return}const headers=rows[0].map(normalise),imported:Game[]=[],skipped:string[]=[];rows.slice(1).forEach((row,index)=>{const line=index+2,team1=column(row,headers,['team 1','team1','home team']),team2=column(row,headers,['team 2','team2','away team']),time=column(row,headers,['time','start','start time']),diamond=column(row,headers,['diamond','field']);if(!team1||!team2||!time||!diamond){skipped.push(`Row ${line}`);return}const requestedCrew=Number(column(row,headers,['crew size','crew','umpires','crew members'])),crew:CrewSize=requestedCrew===3?3:requestedCrew===4?4:2,number=Number(column(row,headers,['game','game number','game #']))||imported.length+1;imported.push({id:`import-${Date.now()}-${index}-${Math.random().toString(36).slice(2,7)}`,number,date:column(row,headers,['date'])||DEFAULT_DATE,start:time,field:diamond,teams:`${team1} vs ${team2}`,division:column(row,headers,['division','competition']),positions:positionsForCrew(crew)})});if(imported.length===0){setMessage('No games uploaded. Required columns are Team 1, Team 2, Time and Diamond.');return}imported.sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.number-b.number);setGames(imported);setEditingId(null);localStorage.setItem('softball-assignments','[]');setMessage(`${imported.length} game${imported.length===1?'':'s'} uploaded${skipped.length?`; ${skipped.length} row${skipped.length===1?'':'s'} skipped`:''}.`)}catch(error){console.error(error);setMessage('Could not read the CSV. Please check that it is a valid CSV file.')}finally{event.target.value=''}};reader.onerror=()=>{setMessage('Could not read that file.');event.target.value=''};reader.readAsText(file)}
 if(!mounted)return <main><div className="loading">Loading schedule…</div></main>
 return <main><header><div><div className="brand">DIAMOND • OFFICIATING</div><h1>Build / Upload Schedule</h1><p>Add games manually or upload a CSV schedule.</p></div><a href="/dashboard">← Dashboard</a></header>
 <section className="card"><div className="section-head"><div><h2>{editingId?`Edit Game ${form.number}`:'Add Game Manually'}</h2><p>End time is not required.</p></div>{editingId&&<button type="button" onClick={resetForm}>Cancel edit</button>}</div><form onSubmit={saveGame}><label>Game number<input type="number" min="1" value={form.number} onChange={event=>setForm({...form,number:Number(event.target.value)})}/></label><label>Date<input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></label><label>Team 1<input value={form.teams.split(/\s+vs\s+/i)[0]||''} onChange={event=>{const parts=form.teams.split(/\s+vs\s+/i);setForm({...form,teams:`${event.target.value} vs ${parts[1]||''}`})}} placeholder="Team 1"/></label><label>Team 2<input value={form.teams.split(/\s+vs\s+/i)[1]||''} onChange={event=>{const parts=form.teams.split(/\s+vs\s+/i);setForm({...form,teams:`${parts[0]||''} vs ${event.target.value}`})}} placeholder="Team 2"/></label><label>Time<input type="time" value={form.start} onChange={event=>setForm({...form,start:event.target.value})}/></label><label>Diamond<input value={form.field} onChange={event=>setForm({...form,field:event.target.value})} placeholder="Diamond 1"/></label><label>Competition / Division<input value={form.division} onChange={event=>setForm({...form,division:event.target.value})} placeholder="Optional"/></label><div className="crew"><strong>Crew size</strong><div>{([2,3,4] as const).map(size=><button type="button" key={size} className={form.positions.length===size?'active':''} onClick={()=>setCrew(size)}>{size}</button>)}</div><small>{crewDescription(form.positions.length)}</small></div>{message&&<div className="message">{message}</div>}<button className="primary" type="submit">{editingId?'Save Game Changes':'+ Add Game'}</button></form></section>
 <section className="card"><div className="section-head"><div><h2>Upload CSV</h2><p>Import Team 1, Team 2, Time, Diamond and Crew Size.</p></div><button type="button" className="upload" onClick={()=>fileInput.current?.click()}>↑ Choose CSV</button><input ref={fileInput} className="hidden" type="file" accept=".csv,text/csv" onChange={uploadCSV}/></div><div className="csv-help"><b>Accepted columns</b><code>Game, Date, Team 1, Team 2, Time, Diamond, Division, Crew Size</code><span>No end-time column is required.</span></div></section>
 <section className="card"><div className="section-head"><div><h2>Current Schedule</h2><p>{games.length} game{games.length===1?'':'s'} in the tournament.</p></div><a href="/dashboard">View allocation dashboard →</a></div><div className="table"><table><thead><tr><th>Game</th><th>Date</th><th>Time</th><th>Diamond</th><th>Teams</th><th>Division</th><th>Crew</th><th>Actions</th></tr></thead><tbody>{games.map(game=><tr key={game.id}><td>#{game.number}</td><td>{game.date}</td><td>{game.start}</td><td>{game.field}</td><td>{game.teams}</td><td>{game.division||'—'}</td><td>{game.positions.length}</td><td><button type="button" onClick={()=>editGame(game)}>Edit</button><button type="button" className="delete" onClick={()=>deleteGame(game.id)}>Delete</button></td></tr>)}</tbody></table></div>{!games.length&&<div className="empty">No games yet. Add one above or upload a CSV.</div>}</section>
 <style jsx>{`main{min-height:100vh;background:#f5f7f8;color:#1c2b33;font-family:Arial,sans-serif;padding-bottom:60px}.loading{min-height:100vh;display:grid;place-items:center;color:#667983}header{background:#fff;border-bottom:1px solid #dde5e9;padding:24px 5%;display:flex;justify-content:space-between;align-items:center}header a,.section-head a{color:#1587b2;text-decoration:none;font-weight:600;font-size:13px}.brand{font-size:11px;letter-spacing:2px;color:#5d7380}h1{margin:5px 0}p{color:#6d7e86;font-size:13px}.card{margin:20px 5%;background:#fff;border:1px solid #dce4e8;border-radius:8px;padding:22px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:18px}.section-head h2{margin:0 0 5px}form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}label{font-size:11px;font-weight:700;color:#536771;display:flex;flex-direction:column;gap:6px}input{padding:10px;border:1px solid #cbd6dc;border-radius:5px;font:inherit;color:#1c2b33}.crew{grid-column:1/-1;display:flex;align-items:center;gap:12px;padding:14px;background:#f7f9fa;border-radius:6px}.crew strong{font-size:12px}.crew button,button{border:1px solid #cbd6dc;background:#fff;border-radius:5px;padding:9px 13px;cursor:pointer}.crew button{padding:7px 13px}.crew button.active,.upload{background:#1587b2;color:#fff;border-color:#1587b2}.crew small{color:#687982}.primary{grid-column:1/-1;background:#1587b2;color:#fff;border-color:#1587b2;font-weight:700}.message{grid-column:1/-1;padding:10px;background:#eef7fa;border:1px solid #c7e2ea;border-radius:5px;color:#356673;font-size:12px}.hidden{display:none}.csv-help{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:12px;background:#f7f9fa;border-radius:6px;font-size:12px;color:#65767e}.csv-help code{background:#fff;border:1px solid #e1e7ea;padding:6px 9px;border-radius:4px}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:11px;border-bottom:1px solid #e7ecef;text-align:left;white-space:nowrap}th{background:#f7f9fa;color:#667983;font-size:9px;letter-spacing:1px}td button{padding:6px 9px;margin-right:5px}.delete{color:#a43d35}.empty{padding:30px;text-align:center;color:#74858d}@media(max-width:800px){form{grid-template-columns:repeat(2,minmax(0,1fr))}.crew{flex-wrap:wrap}header{gap:15px;align-items:flex-start}}@media(max-width:520px){form{grid-template-columns:1fr}.card{margin-left:3%;margin-right:3%}.section-head{align-items:flex-start;flex-direction:column}}`}</style></main>
}
