'use client'

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react'
import { Game } from '../../lib/types'
import { positionsForCrew } from '../components/CrewSizeControls'

const DEFAULT_DATE = '2026-08-30'
const blankGame = (): Game => ({ id:`game-${Date.now()}-${Math.random().toString(36).slice(2,8)}`, number:1, date:DEFAULT_DATE, start:'09:00', field:'Diamond 1', teams:'', division:'', positions:positionsForCrew(2) })
const readGames=():Game[]=>{try{const stored=JSON.parse(localStorage.getItem('softball-games')||'null');return Array.isArray(stored)?stored:[]}catch{return []}}
const parseCSV=(text:string)=>{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell.trim())}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());cell='';if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=c}if(cell.length||row.length){row.push(cell.trim());if(row.some(v=>v.trim()))rows.push(row)}return rows}
const norm=(s:string)=>s.toLowerCase().trim().replace(/\ufeff/g,'').replace(/\s+/g,' ')
const value=(row:string[],headers:string[],names:string[])=>{const i=names.map(norm).map(n=>headers.indexOf(n)).find(i=>i>=0)??-1;return i>=0?(row[i]||'').trim():''}

export default function SchedulePage(){
 const [games,setGames]=useState<Game[]>([]),[mounted,setMounted]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState<Game>(blankGame()),[message,setMessage]=useState('');const fileRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{setGames(readGames());setMounted(true)},[])
 useEffect(()=>{if(mounted)localStorage.setItem('softball-games',JSON.stringify(games))},[games,mounted])
 const resetForm=()=>{const next=games.length?Math.max(...games.map(g=>g.number))+1:1;setForm({...blankGame(),number:next});setEditingId(null)}
 const saveGame=(e:FormEvent)=>{e.preventDefault();if(!form.teams.trim()||!form.field.trim()||!form.start){setMessage('Please enter both teams, time and diamond.');return}if(editingId){setGames(gs=>gs.map(g=>g.id===editingId?form:g));setMessage(`Game ${form.number} updated.`)}else{setGames(gs=>[...gs,form].sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.number-b.number));setMessage(`Game ${form.number} added.`)}resetForm()}
 const editGame=(g:Game)=>{setEditingId(g.id);setForm({...g});setMessage('Editing game. Save changes when finished.');window.scrollTo({top:0,behavior:'smooth'})}
 const deleteGame=(id:string)=>{const g=games.find(x=>x.id===id);if(!g||!confirm(`Delete Game ${g.number}? Existing umpire appointments for this game will also be removed.`))return;setGames(gs=>gs.filter(x=>x.id!==id));try{const a=JSON.parse(localStorage.getItem('softball-assignments')||'[]');localStorage.setItem('softball-assignments',JSON.stringify(a.filter((x:{gameId:string})=>x.gameId!==id)))}catch{}setMessage(`Game ${g.number} deleted.`)}
 const setCrew=(size:2|3|4)=>setForm(g=>({...g,positions:positionsForCrew(size)}))
 const uploadCSV=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setMessage('Reading CSV…');const reader=new FileReader();reader.onload=()=>{try{const rows=parseCSV(String(reader.result??''));if(rows.length<2){setMessage('CSV is empty or has no game rows.');return}const headers=rows[0].map(norm);const imported:Game[]=[];const errors:string[]=[];rows.slice(1).forEach((row,i)=>{const line=i+2;const game=Number(value(row,headers,['game','game number','game #']))||i+1;const date=value(row,headers,['date'])||DEFAULT_DATE;const start=value(row,headers,['time','start','start time']);const diamond=value(row,headers,['diamond','field']);const team1=value(row,headers,['team 1','team1','home team']);const team2=value(row,headers,['team 2','team2','away team']);const teams=team1||team2?`${team1} vs ${team2}`:value(row,headers,['teams','match']);const rawCrew=Number(value(row,headers,['crew size','crew','umpires','crew members']));const crew=(rawCrew===3?3:rawCrew===4?4:2) as 2|3|4;if(!start||!diamond||!team1||!team2){errors.push(`Row ${line}: missing Team 1, Team 2, Time or Diamond`);return}imported.push({id:`import-${Date.now()}-${i}-${Math.random().toString(36).slice(2,6)}`,number:game,date,start,field:diamond,teams,division:value(row,headers,['division','competition']),positions:positionsForCrew(crew)})});if(!imported.length){setMessage(errors.length?`No games uploaded. ${errors[0]}`:'No valid games found.');return}setGames(imported.sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.number-b.number));setEditingId(null);localStorage.setItem('softball-assignments','[]');setMessage(`${imported.length} game${imported.length===1?'':'s'} uploaded successfully.${errors.length?` ${errors.length} row${errors.length===1?'':'s'} skipped.`:''}`)}catch(err){console.error(err);setMessage('Could not read the CSV. Check the header names and file format.')}};reader.onerror=()=>setMessage('Could not read that file.');reader.readAsText(file);e.target.value=''}}
 if(!mounted)return <main><div className="loading">Loading schedule…</div></main>
 return <main><header><div><div className="brand">DIAMOND • OFFICIATING</div><h1>Build / Upload Schedule</h1><p>Add games manually or upload a CSV.</p></div><a href="/dashboard">← Dashboard</a></header>
 <section className="card"><div className="section-head"><div><h2>{editingId?`Edit Game ${form.number}`:'Add Game Manually'}</h2><p>Enter the game details below. End time is not required.</p></div>{editingId&&<button onClick={resetForm}>Cancel edit</button>}</div>
 <form onSubmit={saveGame}><label>Game number<input type="number" min="1" value={form.number} onChange={e=>setForm({...form,number:Number(e.target.value)})}/></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Team 1<input value={form.teams.split(/\s+vs\s+/i)[0]||''} onChange={e=>{const p=form.teams.split(/\s+vs\s+/i);setForm({...form,teams:`${e.target.value} vs ${p[1]||''}`})}} placeholder="Team 1"/></label><label>Team 2<input value={form.teams.split(/\s+vs\s+/i)[1]||''} onChange={e=>{const p=form.teams.split(/\s+vs\s+/i);setForm({...form,teams:`${p[0]||''} vs ${e.target.value}`})}} placeholder="Team 2"/></label><label>Time<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Diamond<input value={form.field} onChange={e=>setForm({...form,field:e.target.value})} placeholder="Diamond 1"/></label><label>Competition / Division<input value={form.division} onChange={e=>setForm({...form,division:e.target.value})} placeholder="Optional"/></label>
 <div className="crew"><span>Crew size</span><div>{([2,3,4] as const).map(size=><button type="button" key={size} className={form.positions.length===size?'active':''} onClick={()=>setCrew(size)}>{size}</button>)}</div><small>{form.positions.length===2?'Plate + 1st Base':form.positions.length===3?'Plate + 1st Base + 3rd Base':'Plate + 1st Base + 2nd Base + 3rd Base'}</small></div>{message&&<div className="message">{message}</div>}<button className="primary" type="submit">{editingId?'Save Game Changes':'+ Add Game'}</button></form></section>
 <section className="card"><div className="section-head"><div><h2>Upload CSV</h2><p>Upload a schedule using Team 1, Team 2, Time, Diamond and Crew Size.</p></div><button type="button" className="upload" onClick={()=>fileRef.current?.click()}>↑ Choose CSV</button><input ref={fileRef} className="hidden" type="file" accept=".csv,text/csv,application/vnd.ms-excel" onChange={uploadCSV}/></div><div className="csv-help"><b>Accepted columns</b><code>Game, Date, Team 1, Team 2, Time, Diamond, Division, Crew Size</code><span>End time is not required. Crew Size must be 2, 3 or 4.</span></div></section>
 <section className="card"><div className="section-head"><div><h2>Current Schedule</h2><p>{games.length} game{games.length===1?'':'s'} in the tournament.</p></div><a href="/dashboard">View allocation dashboard →</a></div><div className="table"><table><thead><tr><th>Game</th><th>Date</th><th>Time</th><th>Diamond</th><th>Teams</th><th>Division</th><th>Crew</th><th>Actions</th></tr></thead><tbody>{games.map(g=><tr key={g.id}><td>#{g.number}</td><td>{g.date}</td><td>{g.start}</td><td>{g.field}</td><td>{g.teams}</td><td>{g.division||'—'}</td><td>{g.positions.length}</td><td><button onClick={()=>editGame(g)}>Edit</button><button className="delete" onClick={()=>deleteGame(g.id)}>Delete</button></td></tr>)}</tbody></table></div>{!games.length&&<div className="empty">No games yet. Add one above or upload a CSV.</div>}</section>
 <style jsx>{`main{min-height:100vh;background:#f5f7f8;color:#1c2b33;font-family:Arial,sans-serif;padding-bottom:60px}.loading{min-height:100vh;display:grid;place-items:center;color:#667983}header{background:#fff;border-bottom:1px solid #dde5e9;padding:24px 5%;display:flex;justify-content:space-between;align-items:center}header a,.section-head a{color:#1587b2;text-decoration:none;font-weight:600;font-size:13px}.brand{font-size:11px;letter-spacing:2px;color:#5d7380}h1{margin:5px 0}p{color:#6d7e86;font-size:13px}.card{margin:20px 5%;background:#fff;border:1px solid #dce4e8;border-radius:8px;padding:22px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.section-head h2{margin:0 0 5px}form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}label{font-size:11px;font-weight:700;color:#536771;display:flex;flex-direction:column;gap:6px}input{padding:10px;border:1px solid #cbd6dc;border-radius:5px;font:inherit;color:#1c2b33}.crew{grid-column:1/-1;display:flex;align-items:center;gap:12px;padding:14px;background:#f7f9fa;border-radius:6px}.crew span{font-size:12px;font-weight:700}.crew button,button{border:1px solid #cbd6dc;background:#fff;border-radius:5px;padding:9px 13px;cursor:pointer}.crew button{padding:7px 13px}.crew button.active,.upload{background:#1587b2;color:#fff;border-color:#1587b2}.crew small{color:#687982}.primary{grid-column:1/-1;background:#1587b2;color:#fff;border-color:#1587b2;font-weight:700}.message{grid-column:1/-1;padding:10px;background:#eef7fa;border:1px solid #c7e2ea;border-radius:5px;color:#356673;font-size:12px}.hidden{display:none}.csv-help{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:12px;background:#f7f9fa;border-radius:6px;font-size:12px;color:#65767e}.csv-help code{background:#fff;border:1px solid #e1e7ea;padding:6px 9px;border-radius:4px}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:11px;border-bottom:1px solid #e7ecef;text-align:left;white-space:nowrap}th{background:#f7f9fa;color:#667983;font-size:9px;letter-spacing:1px}td button{padding:6px 9px;margin-right:5px}.delete{color:#a43d35}.empty{padding:30px;text-align:center;color:#74858d}@media(max-width:800px){form{grid-template-columns:repeat(2,minmax(0,1fr))}header{gap:15px;align-items:flex-start}.crew{flex-wrap:wrap}}@media(max-width:520px){form{grid-template-columns:1fr}.card{margin-left:3%;margin-right:3%}.section-head{align-items:flex-start;gap:10px;flex-direction:column}}`}</style></main>
}
