'use client'
import {useEffect,useState} from 'react'
import {TOURNAMENT_RULES,DEFAULT_RULE_IDS} from '../../lib/tournament-rules'
export default function RulesPage(){
 const [enabled,setEnabled]=useState<string[]>(DEFAULT_RULE_IDS); const [saved,setSaved]=useState(false)
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('softball-enabled-rules')||'null');if(Array.isArray(x))setEnabled(x)}catch{}},[])
 const toggle=(id:string)=>setEnabled(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id])
 const save=()=>{localStorage.setItem('softball-enabled-rules',JSON.stringify(enabled));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 const group=(title:string,items:any[])=><section className="rulegroup"><div className="grouphead"><h3>{title}</h3><span>{items.filter(r=>enabled.includes(r.id)).length}/{items.length} selected</span></div>{items.map(r=><label className={`rule ${enabled.includes(r.id)?'selected':''}`} key={r.id}><input type="checkbox" checked={enabled.includes(r.id)} onChange={()=>toggle(r.id)}/><div className="check">{enabled.includes(r.id)?'✓':''}</div><div className="rulecopy"><div><b>{r.name}</b><span className={`rulebadge ${r.category}`}>{r.category==='hard'?'HARD':'SOFT'}</span></div><p>{r.description}</p></div></label>)}</section>
 const hard=TOURNAMENT_RULES.filter(r=>r.category==='hard'); const soft=TOURNAMENT_RULES.filter(r=>r.category==='soft'); const balance=soft.filter(r=>['one-plate','workload-balance','plate-balance'].includes(r.id)); const special=soft.filter(r=>!['one-plate','workload-balance','plate-balance'].includes(r.id))
 return <main><header className="topbar"><div><div className="brand">DIAMOND <span>•</span> OFFICIATING</div><h1>Tournament Rules</h1></div><div className="header-actions"><button className="secondary" onClick={()=>location.href='/'}>← Dashboard</button><button className="primary" onClick={save}>✓ {saved?'Rules Saved':'Save Tournament Rules'}</button></div></header><section className="hero compact"><div><p className="eyebrow">TOURNAMENT CONFIGURATION</p><h2>Rules & Allocation Preferences</h2><p>Select the rules that apply to this tournament. Hard rules constrain the allocator; soft rules influence which valid allocation is preferred.</p></div></section><section className="ruleintro"><div><strong>{enabled.length}</strong><span>rules selected</span></div><div><strong>{enabled.filter(id=>hard.some(r=>r.id===id)).length}</strong><span>hard rules</span></div><div><strong>{enabled.filter(id=>soft.some(r=>r.id===id)).length}</strong><span>soft rules</span></div></section>{group('Core rules',hard)}{group('Workload & balance',balance)}{group('Tournament-specific',special)}<footer>RULES ARE SAVED TO THIS BROWSER FOR THE CURRENT TOURNAMENT</footer></main>}
