'use client'

import { useEffect, useState } from 'react'
import { getTournamentOverview } from '../../../lib/supabase/tournaments'
import { getSupabaseClient } from '../../../lib/supabase/client'

export default function TournamentOverview({params}:{params:{tournamentId:string}}){
 const [data,setData]=useState<Awaited<ReturnType<typeof getTournamentOverview>>|null>(null),[error,setError]=useState('')
 useEffect(()=>{getTournamentOverview(params.tournamentId).then(setData).catch(e=>setError(e instanceof Error?e.message:'Could not load tournament.'))},[params.tournamentId])
 if(error)return <main><div className="error"><h1>Unable to load tournament</h1><p>{error}</p><a href="/tournaments">← My Tournaments</a></div></main>
 if(!data)return <main><div className="loading">Loading tournament…</div></main>
 const id=params.tournamentId
 const links=[['Overview',`/tournament/${id}`],['Schedule',`/schedule?tournamentId=${id}`],['Umpires',`/dashboard?tournamentId=${id}`],['Rules',`/rules?tournamentId=${id}`],['Print',`/print?tournamentId=${id}`]]
 const first=data.dates[0],last=data.dates[data.dates.length-1]
 return <main><header><div><a href="/tournaments">← My Tournaments</a><div className="brand">DIAMOND • OFFICIATING</div><h1>{data.tournament.name}</h1><p>Tournament workspace</p></div></header><nav>{links.map(([label,href])=><a className={label==='Overview'?'active':''} key={label} href={href}>{label}</a>)}</nav><section className="stats"><div><b>{data.days.length}</b><span>Days</span></div><div><b>{data.gameCount}</b><span>Games</span></div><div><b>{data.umpireCount}</b><span>Umpires</span></div></section><section className="card"><h2>Tournament</h2><p>{first&&last?first===last?first:`${first} to ${last}`:'Dates not set'}</p><div className="actions"><a href={`/schedule?tournamentId=${id}`}>Build Schedule</a><a href={`/dashboard?tournamentId=${id}`}>Manage Umpires / Allocations</a><a href={`/print?tournamentId=${id}`}>Print</a></div></section><section className="card"><h2>Tournament Days</h2><div className="days">{data.days.map(day=><div key={day.id}><b>{day.name}</b><span>{day.date||'Date not set'}</span></div>)}</div></section><style jsx>{`main{min-height:100vh;background:#f5f7f8;color:#1c2b33;font-family:Arial,sans-serif;padding-bottom:60px}header{background:#fff;border-bottom:1px solid #dde5e9;padding:26px 6%}header>a{color:#1587b2;text-decoration:none;font-size:13px;font-weight:700}.brand{font-size:11px;letter-spacing:2px;color:#5d7380;margin-top:18px}h1{margin:5px 0;font-size:32px}p{color:#6d7e86;font-size:13px}nav{display:flex;gap:6px;padding:14px 6%;overflow:auto}nav a{padding:9px 13px;background:#fff;border:1px solid #d5dfe3;border-radius:6px;text-decoration:none;color:#40545d;font-size:12px;white-space:nowrap}nav a.active{background:#1587b2;color:#fff;border-color:#1587b2}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:8px 6% 0}.stats div{background:#fff;border:1px solid #dce4e8;border-radius:9px;padding:20px}.stats b{display:block;font-size:28px}.stats span{font-size:11px;color:#71828a}.card{margin:18px 6%;background:#fff;border:1px solid #dce4e8;border-radius:9px;padding:22px}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.actions a{background:#1587b2;color:#fff;text-decoration:none;padding:10px 13px;border-radius:6px;font-size:12px;font-weight:700}.days{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px}.days div{background:#f7f9fa;padding:12px;border-radius:6px}.days span{display:block;color:#71828a;font-size:11px;margin-top:4px}.loading{text-align:center;padding:70px}.error{margin:40px auto;max-width:600px;padding:25px;background:#fff1ef;border:1px solid #e4b9b3;border-radius:8px}.error a{color:#1587b2}@media(max-width:600px){.stats{grid-template-columns:1fr 1fr}.stats div:last-child{grid-column:1/-1}}`}</style></main>
}
