'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { allocate, validateUmpire } from '../lib/rules'
import { Assignment, Game, Position, Umpire } from '../lib/types'

const CREWS: Record<number, Position[]> = { 2: ['Plate', 'Base'], 3: ['Plate', 'Base 1', 'Base 2'], 4: ['Plate', 'Base 1', 'Base 2', 'Base 3'] }
const ALL_POSITIONS: Position[] = ['Plate', 'Base', 'Base 1', 'Base 2', 'Base 3']
const DEFAULT_GAMES: Game[] = [
{id:'g1',number:1,date:'2026-08-30',start:'09:00',end:'10:20',field:'Field 1',teams:'NZ vs Australia',division:'Senior Women',positions:CREWS[2]},
{id:'g2',number:2,date:'2026-08-30',start:'10:30',end:'11:50',field:'Field 1',teams:'Japan vs USA',division:'Senior Women',positions:CREWS[2]},
{id:'g3',number:3,date:'2026-08-30',start:'12:00',end:'13:20',field:'Field 1',teams:'Canada vs Mexico',division:'Senior Women',positions:CREWS[2]},
{id:'g4',number:4,date:'2026-08-30',start:'13:30',end:'14:50',field:'Field 1',teams:'Australia vs Japan',division:'Senior Women',positions:CREWS[2]},
{id:'g5',number:5,date:'2026-08-30',start:'15:00',end:'16:20',field:'Field 1',teams:'USA vs NZ',division:'Senior Women',positions:CREWS[2]},
{id:'g6',number:6,date:'2026-08-30',start:'16:30',end:'17:50',field:'Field 1',teams:'Mexico vs Canada',division:'Senior Women',positions:CREWS[2]}]
const DEFAULT_UMPIRES: Umpire[] = [
{id:'u1',name:'Smith',availability:'All day',maxGames:3,experience:'International'},
{id:'u2',name:'Jones',availability:'All day',maxGames:3,experience:'National'},
{id:'u3',name:'Brown',availability:'All day',maxGames:3,experience:'National'},
{id:'u4',name:'Wilson',availability:'All day',maxGames:3,experience:'Regional'}]
function read<T>(key:string,fallback:T):T{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
function crew(n:number){return CREWS[Math.min(4,Math.max(2,n))]}
function normaliseGames(gs:Game[]){return gs.map(g=>({...g,positions:g.positions?.length>=2?g.positions:CREWS[2]}))}
function sameAssignments(a:Assignment[],b:Assignment[]){const key=(x:Assignment)=>`${x.gameId}|${x.position}|${x.umpireId}`;return JSON.stringify([...a].map(key).sort())===JSON.stringify([...b].map(key).sort())}

export default function Home(){
 const [games,setGames]=useState<Game[]>(DEFAULT_GAMES),[umpires,setUmpires]=useState<Umpire[]>(DEFAULT_UMPIRES)
 const [committed,setCommitted]=useState<Assignment[]>([]),[draft,setDraft]=useState<Assignment[]>([])
 const [view,setView]=useState<'dashboard'|'schedule'|'umpires'>('dashboard'),[notice,setNotice]=useState('Ready to allocate')
 const [gameForm,setGameForm]=useState({date:'2026-08-30',start:'09:00',end:'10:20',field:'Field 1',teams:'',division:'',crew:2})
 const [umpForm,setUmpForm]=useState({name:'',availability:'All day',maxGames:3,experience:'National' as Umpire['experience']})
 useEffect(()=>{const g=normaliseGames(read('softball-games',DEFAULT_GAMES));const u=read('softball-umpires',DEFAULT_UMPIRES);const a=read<Assignment[]>('softball-assignments',[]);setGames(g);setUmpires(u);setCommitted(a);setDraft(a)},[])
 useEffect(()=>{localStorage.setItem('softball-games',JSON.stringify(games))},[games]);useEffect(()=>{localStorage.setItem('softball-umpires',JSON.stringify(umpires))},[umpires])
 const issues=useMemo(()=>umpires.flatMap(u=>validateUmpire(u,games,draft)),[umpires,games,draft]),hard=issues.filter(x=>x.severity==='hard'),soft=issues.filter(x=>x.severity==='soft'),dirty=!sameAssignments(committed,draft)
 const nameOf=(id:string)=>umpires.find(u=>u.id===id)?.name||'Unallocated';const assignedGames=(id:string)=>new Set(draft.filter(a=>a.umpireId===id).map(a=>a.gameId)).size
 const assign=(game:Game,position:Position,value:string)=>{const trial=draft.filter(a=>!(a.gameId===game.id&&a.position===position));if(value)trial.push({gameId:game.id,umpireId:value,position});const u=value?umpires.find(x=>x.id===value):undefined;if(u){const hv=validateUmpire(u,games,trial).filter(x=>x.severity==='hard');if(hv.length&&!window.confirm(`Override Rule?\n\n${hv[0].message}\n\nThis change will remain a draft and the violation will stay visible.`))return}setDraft(trial);setNotice('Draft allocation changed. Commit when ready.')}
 const auto=()=>{const r=allocate(games,umpires);setDraft(r.assignments);setNotice(r.unallocated.length?`${r.unallocated.length} slot(s) remain open because filling them would break a hard rule.`:'Auto allocation complete. Review and commit the allocation.')}
 const commit=()=>{if(!dirty){setNotice('No allocation changes to commit.');return}if(hard.length&&!window.confirm(`There are ${hard.length} hard rule violation(s). Commit these explicit overrides anyway?\n\nThe violations will remain visible.`))return;localStorage.setItem('softball-assignments',JSON.stringify(draft));setCommitted(draft);setNotice(hard.length?'Allocation committed with explicit overrides.':'Allocation committed. Dashboard, workload and saved data are updated.');window.scrollTo({top:0,behavior:'smooth'})}
 const resetDraft=()=>{setDraft(committed);setNotice('Draft changes discarded. Last committed allocation restored.')}
 const addGame=()=>{const n=Math.max(0,...games.map(g=>g.number))+1;setGames([...games,{id:`g${Date.now()}`,number:n,...gameForm,positions:crew(gameForm.crew)}]);setGameForm({...gameForm,teams:'',division:''});setNotice('Game added. Review the schedule before allocating.')}
 const addUmpire=()=>{if(!umpForm.name.trim())return;setUmpires([...umpires,{...umpForm,id:`u${Date.now()}`}]);setUmpForm({...umpForm,name:''});setNotice('Umpire added to roster.')}
 const importCSV=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const rows=String(reader.result).trim().split(/\r?\n/).map(r=>r.split(',').map(x=>x.trim().replace(/^"|"$/g,'')));const header=rows.shift()?.map(x=>x.toLowerCase())||[];const get=(r:string[],names:string[])=>{const i=names.map(n=>header.indexOf(n)).find(i=>i>=0)??-1;return i>=0?r[i]||'':''};const imported=rows.filter(r=>r.length>1).map((r,i)=>({id:`import-${Date.now()}-${i}`,number:Number(get(r,['game','game number']))||i+1,date:get(r,['date'])||gameForm.date,start:get(r,['start','start time']),end:get(r,['end','end time']),field:get(r,['field']),teams:get(r,['teams','match']),division:get(r,['division','competition']),positions:crew(Number(get(r,['umpires','crew','crew size']))||2)}));setGames(imported);setDraft([]);setCommitted([]);localStorage.setItem('softball-assignments','[]');setNotice(`${imported.length} games imported. Allocation reset.`)};reader.readAsText(file)}
 const exportCSV=()=>{const headers='Game,Date,Start,End,Field,Teams,Division,Umpires,Plate,Base,Base 1,Base 2,Base 3';const rows=games.map(g=>[g.number,g.date,g.start,g.end,g.field,g.teams,g.division,g.positions.length,...ALL_POSITIONS.map(p=>g.positions.includes(p)?nameOf(draft.find(a=>a.gameId===g.id&&a.position===p)?.umpireId||''):'')].join(','));const blob=new Blob([headers+'\n'+rows.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='umpire-allocation.csv';a.click()}
 const scheduleTable=<section className="card"><div className="card-head"><div><h3>Game Schedule</h3><p>2, 3 or 4-umpire crews with live rule validation</p></div><div className="legend"><span>🟢 Valid</span><span>🟠 Soft warning</span><span>🔴 Violation</span></div></div><div className="table-wrap"><table><thead><tr><th>GAME</th><th>TIME</th><th>FIELD</th><th>TEAMS / DIVISION</th><th>CREW</th>{ALL_POSITIONS.map(p=><th key={p}>{p.toUpperCase()}</th>)}<th>STATUS</th></tr></thead><tbody>{games.map(g=>{const gv=issues.filter(v=>v.gameId===g.id),complete=g.positions.every(p=>draft.some(a=>a.gameId===g.id&&a.position===p));return <tr key={g.id}><td><b>#{g.number}</b></td><td>{g.start}<small>– {g.end}</small></td><td>{g.field}</td><td><b>{g.teams}</b><small>{g.division}</small></td><td><span className="crewtag">{g.positions.length}</span></td>{ALL_POSITIONS.map(p=>g.positions.includes(p)?<td key={p}><select value={draft.find(a=>a.gameId===g.id&&a.position===p)?.umpireId||''} onChange={e=>assign(g,p,e.target.value)}><option value="">Unallocated</option>{umpires.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></td>:<td key={p} className="muted">—</td>)}<td><span className={`badge ${gv.some(v=>v.severity==='hard')?'bad':gv.length?'warn':complete?'good':'warn'}`}>{gv.some(v=>v.severity==='hard')?'Violation':gv.length?'Soft warning':complete?'Valid':'Open'}</span></td></tr>})}</tbody></table></div></section>
 const workload=<section className="card"><div className="card-head"><div><h3>Umpire Workload</h3><p>One Plate per day is a soft preference, not a hard constraint</p></div></div><div className="table-wrap"><table><thead><tr><th>UMPIRE</th><th>GAMES</th><th>PLATE</th><th>BASE</th><th>STATUS</th></tr></thead><tbody>{umpires.map(u=>{const mine=draft.filter(a=>a.umpireId===u.id),plates=mine.filter(a=>a.position==='Plate').length,v=issues.filter(x=>x.umpireId===u.id);return <tr key={u.id}><td><b>{u.name}</b><small>{u.experience} · {u.availability}</small></td><td><b>{assignedGames(u.id)}/{u.maxGames}</b></td><td>{plates}</td><td>{mine.filter(a=>a.position!=='Plate').length}</td><td><span className={`badge ${v.some(x=>x.severity==='hard')?'bad':v.length?'warn':assignedGames(u.id)>=u.maxGames?'warn':'good'}`}>{v.some(x=>x.severity==='hard')?'Rule violation':v.length?'Soft warning':assignedGames(u.id)>=u.maxGames?'Max reached':'Available'}</span></td></tr>})}</tbody></table></div></section>
 return <main><header className="topbar"><div><div className="brand">DIAMOND <span>•</span> OFFICIATING</div><h1>Umpire Allocation</h1></div><div className="header-actions"><span className="pill">2–4 UMPIRE CREW</span><button className="secondary" onClick={exportCSV}>Export CSV</button><button className="primary" onClick={auto}>⚡ Auto Allocate</button></div></header><nav className="mainnav"><button className={view==='dashboard'?'active':''} onClick={()=>setView('dashboard')}>Dashboard</button><button className={view==='schedule'?'active':''} onClick={()=>setView('schedule')}>Build / Upload Schedule</button><button className={view==='umpires'?'active':''} onClick={()=>setView('umpires')}>Umpires</button></nav>
 {dirty&&<div className="commitbar"><div><b>Draft allocation changes</b><span>{hard.length?`${hard.length} hard issue(s) · ${soft.length} soft warning(s)`:'Review complete. Ready to commit.'}</span></div><div><button className="secondary" onClick={resetDraft}>Discard Changes</button><button className="primary" onClick={commit}>✓ Commit Allocation</button></div></div>}
 {view==='dashboard'&&<><section className="hero"><div><p className="eyebrow">TOURNAMENT CONTROL</p><h2>Allocation Dashboard</h2><p>Each game can use 2, 3 or 4 umpires. Hard rules are enforced; soft preferences guide the best allocation.</p></div><div className="status"><span className={`dot ${hard.length?'warn':''}`}></span>{notice}</div></section><section className="metrics"><div><span>GAMES</span><strong>{games.length}</strong><small>Scheduled</small></div><div><span>UMPIRES</span><strong>{umpires.length}</strong><small>In roster</small></div><div><span>ALLOCATED</span><strong>{new Set(draft.map(a=>a.gameId)).size}<em>/{games.length}</em></strong><small>Games with a slot</small></div><div className={hard.length?'danger':''}><span>HARD ISSUES</span><strong>{hard.length}</strong><small>{soft.length?`${soft.length} soft warning(s)`:hard.length?'Needs attention':'All clear'}</small></div></section>{scheduleTable}{workload}</>}
 {view==='schedule'&&<><section className="hero compact"><div><p className="eyebrow">SCHEDULE BUILDER</p><h2>Build or Upload Schedule</h2><p>Choose 2, 3 or 4 umpires for each game. Four is available when required, but is not mandatory.</p></div></section><section className="builder-grid"><div className="card pad"><h3>Upload CSV</h3><p>Columns: Game, Date, Start, End, Field, Teams, Division. Optional Umpires/Crew column accepts 2, 3 or 4.</p><label className="upload">Choose CSV<input type="file" accept=".csv,text/csv" onChange={importCSV}/></label></div><div className="card pad"><h3>Add game</h3><div className="formgrid"><input type="date" value={gameForm.date} onChange={e=>setGameForm({...gameForm,date:e.target.value})}/><input type="time" value={gameForm.start} onChange={e=>setGameForm({...gameForm,start:e.target.value})}/><input type="time" value={gameForm.end} onChange={e=>setGameForm({...gameForm,end:e.target.value})}/><input placeholder="Field" value={gameForm.field} onChange={e=>setGameForm({...gameForm,field:e.target.value})}/><input placeholder="Teams" value={gameForm.teams} onChange={e=>setGameForm({...gameForm,teams:e.target.value})}/><input placeholder="Division" value={gameForm.division} onChange={e=>setGameForm({...gameForm,division:e.target.value})}/><select value={gameForm.crew} onChange={e=>setGameForm({...gameForm,crew:Number(e.target.value)})}><option value="2">2 umpires</option><option value="3">3 umpires</option><option value="4">4 umpires</option></select></div><button className="primary wide" onClick={addGame}>+ Add Game</button></div></section>{scheduleTable}</>}
 {view==='umpires'&&<><section className="hero compact"><div><p className="eyebrow">ROSTER MANAGEMENT</p><h2>Umpire Roster</h2><p>Add, edit and remove umpires used by the allocation engine.</p></div></section><section className="card pad"><h3>Add umpire</h3><div className="formgrid umpform"><input placeholder="Full name" value={umpForm.name} onChange={e=>setUmpForm({...umpForm,name:e.target.value})}/><input placeholder="Availability" value={umpForm.availability} onChange={e=>setUmpForm({...umpForm,availability:e.target.value})}/><input type="number" min="1" max="3" value={umpForm.maxGames} onChange={e=>setUmpForm({...umpForm,maxGames:Number(e.target.value)})}/><select value={umpForm.experience} onChange={e=>setUmpForm({...umpForm,experience:e.target.value as Umpire['experience']})}><option>International</option><option>National</option><option>Regional</option><option>Developing</option></select><button className="primary" onClick={addUmpire}>+ Add Umpire</button></div></section><section className="card pad"><h3>Current roster</h3><div className="roster">{umpires.map(u=><div className="roster-row" key={u.id}><div><b>{u.name}</b><small>{u.experience} · {u.availability}</small></div><label>Max <input type="number" min="1" max="3" value={u.maxGames} onChange={e=>setUmpires(umpires.map(x=>x.id===u.id?{...x,maxGames:Number(e.target.value)}:x))}/></label><button className="delete" onClick={()=>{if(confirm(`Remove ${u.name}?`)){setUmpires(umpires.filter(x=>x.id!==u.id));setDraft(draft.filter(a=>a.umpireId!==u.id))}}}>Remove</button></div>)}</div></section>{workload}</>}
 <section className="rules"><div><p className="eyebrow">RULE ENGINE</p><h3>Hard rules first. Soft preferences second.</h3><p>Allocation changes are drafts until you explicitly commit them.</p></div><div className="rule-list"><article><strong>01</strong><div><b>Maximum 3 games</b><span>Hard rule. A fourth game cannot be auto-allocated.</span></div></article><article><strong>02</strong><div><b>Back-to-back = Base → Plate</b><span>Hard rule. The next scheduled game counts as consecutive.</span></div></article><article><strong>03</strong><div><b>Plate requires a break</b><span>Hard rule. The next scheduled game must be off.</span></div></article><article><strong>04</strong><div><b>One Plate per day</b><span>Soft rule. A second Plate is allowed if necessary.</span></div></article></div></section>{issues.length>0&&<section className="alerts"><h3>Allocation checks</h3>{issues.map((v,i)=><div key={i}>{v.severity==='hard'?'🔴':'🟠'} <b>{nameOf(v.umpireId)}</b> · {v.message}</div>)}</section>}<footer>DIAMOND OFFICIATING · Rules-first tournament scheduling</footer></main>
}
