'use client'
import { useEffect, useMemo, useState } from 'react'
import { allocateUnlocked, validateUmpire } from '../../lib/rules'
import { Assignment, Game, Position, Umpire } from '../../lib/types'

const POSITIONS:Position[]=['Plate','Base','Base 1','Base 2','Base 3']
const read=<T,>(k:string,f:T):T=>{try{return typeof window==='undefined'?f:JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
const key=(a:Assignment)=>`${a.gameId}|${a.position}`

export default function AllocationControl(){
 const [games,setGames]=useState<Game[]>([]),[umpires,setUmpires]=useState<Umpire[]>([]),[draft,setDraft]=useState<Assignment[]>([]),[locked,setLocked]=useState<string[]>([]),[notice,setNotice]=useState('Allocation control ready')
 useEffect(()=>{setGames(read('softball-games',[]));setUmpires(read('softball-umpires',[]));setDraft(read('softball-assignments',[]));setLocked(read('softball-locked',[]))},[])
 const issues=useMemo(()=>umpires.flatMap(u=>validateUmpire(u,games,draft)),[umpires,games,draft]);const hard=issues.filter(x=>x.severity==='hard'),soft=issues.filter(x=>x.severity==='soft')
 const toggle=(a:Assignment)=>{const k=key(a);setLocked(x=>x.includes(k)?x.filter(v=>v!==k):[...x,k]);setNotice(locked.includes(k)?'Assignment unlocked.':'Assignment locked and protected from re-allocation.')}
 const reallocate=()=>{const keep=draft.filter(a=>locked.includes(key(a)));const result=allocateUnlocked(games,umpires,keep);setDraft(result.assignments);localStorage.setItem('softball-assignments',JSON.stringify(result.assignments));setNotice(result.unallocated.length?`${result.unallocated.length} unlocked slot(s) remain open.`:'Unlocked assignments reallocated. Locked assignments preserved.')}
 const timeline=(u:Umpire)=><div className="timeline">{games.filter(g=>draft.some(a=>a.gameId===g.id&&a.umpireId===u.id)).sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`)).map(g=>{const a=draft.find(x=>x.gameId===g.id&&x.umpireId===u.id)!;return <div className={`timeitem ${a.position==='Plate'?'plate':''}`} key={g.id}><span>{g.start}</span><b>G{g.number}</b><em>{a.position}</em>{locked.includes(key(a))&&<small>🔒</small>}</div>})}</div>
 return <main><header className="topbar"><div><div className="brand">DIAMOND <span>•</span> OFFICIATING</div><h1>Allocation Control</h1></div><div className="header-actions"><button className="secondary" onClick={()=>location.href='/'}>← Dashboard</button><button className="primary" onClick={reallocate}>↻ Re-allocate Unlocked</button></div></header><section className="hero compact"><div><p className="eyebrow">CONTROL CENTRE</p><h2>Protect decisions. Rebuild the rest.</h2><p>Lock assignments you want to keep, then re-allocate only the unlocked slots.</p></div><div className="status"><span className="dot"></span>{notice}</div></section><section className="control-card"><div><b>🔒 {locked.length} locked assignments</b><span>Locked slots survive re-allocation.</span></div><div><b>{hard.length?'🔴':'🟢'} {hard.length} hard issues</b><span>{soft.length} soft warnings</span></div><button className="secondary" onClick={()=>{localStorage.setItem('softball-assignments',JSON.stringify(draft));setNotice('Current allocation saved.')}}>Save Current</button></section><section className="card"><div className="card-head"><div><h3>Lock individual assignments</h3><p>Use the lock icon to protect a specific umpire/position on a game.</p></div></div><div className="table-wrap"><table><thead><tr><th>GAME</th><th>TIME</th><th>FIELD</th>{POSITIONS.map(p=><th key={p}>{p.toUpperCase()}</th>)}<th>STATUS</th></tr></thead><tbody>{games.map(g=><tr key={g.id}><td><b>#{g.number}</b></td><td>{g.start}<small>– {g.end}</small></td><td>{g.field}</td>{POSITIONS.map(p=>{const a=draft.find(x=>x.gameId===g.id&&x.position===p);return g.positions.includes(p)?<td key={p}><div className="lockslot"><span>{a?umpires.find(u=>u.id===a.umpireId)?.name:'Unallocated'}</span>{a&&<button className={`lock ${locked.includes(key(a))?'locked':''}`} onClick={()=>toggle(a)}>{locked.includes(key(a))?'🔒':'🔓'}</button>}</div></td>:<td key={p} className="muted">—</td>})}<td><span className={`badge ${issues.some(v=>v.gameId===g.id&&v.severity==='hard')?'bad':issues.some(v=>v.gameId===g.id)?'warn':'good'}`}>{issues.some(v=>v.gameId===g.id&&v.severity==='hard')?'Violation':issues.some(v=>v.gameId===g.id)?'Warning':'Valid'}</span></td></tr>)}</tbody></table></div></section><section className="card"><div className="card-head"><div><h3>Umpire timelines</h3><p>Game-by-game sequence for quick visual review.</p></div></div><div className="timeline-grid">{umpires.map(u=><article key={u.id}><b>{u.name}</b><small>{new Set(draft.filter(a=>a.umpireId===u.id).map(a=>a.gameId)).size}/{u.maxGames} games · {draft.filter(a=>a.umpireId===u.id&&a.position==='Plate').length} Plate</small>{timeline(u)}</article>)}</div></section><footer>DIAMOND OFFICIATING · Allocation Control</footer></main>
}
