'use client'

import { useEffect, useState } from 'react'
import { createTournamentWithDays, getTournamentSummaries, type TournamentSummary } from '../../lib/supabase/tournaments'

const fmtDate=(value:string)=>new Intl.DateTimeFormat('en-NZ',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value))

export default function TournamentsPage(){
 const [items,setItems]=useState<TournamentSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[creating,setCreating]=useState(false),[name,setName]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setItems(await getTournamentSummaries())}catch(e){setError(e instanceof Error?e.message:'Could not load tournaments.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;setCreating(true);setError('');try{const t=await createTournamentWithDays(name);window.location.href=`/tournament/${t.id}`}catch(e){setError(e instanceof Error?e.message:'Could not create tournament.')}finally{setCreating(false)}}
 return <main><header><div><div className="brand">DIAMOND • OFFICIATING</div><h1>My Tournaments</h1><p>Your tournaments and scheduling workspaces.</p></div></header>
 <section className="toolbar"><button className="primary" onClick={()=>setCreating(true)}>+ Create Tournament</button></section>
 {creating&&<section className="card"><h2>Create Tournament</h2><form onSubmit={create}><input autoFocus placeholder="Tournament name" value={name} onChange={e=>setName(e.target.value)} /><div><button type="button" onClick={()=>{setCreating(false);setName('')}}>Cancel</button><button className="primary" disabled={!name.trim()}>Create</button></div></form></section>}
 {error&&<div className="error">{error}<button onClick={load}>Retry</button></div>}
 {loading?<div className="loading">Loading tournaments…</div>:!items.length&&!error?<section className="empty"><h2>No tournaments yet</h2><p>Create your first tournament to get started.</p><button className="primary" onClick={()=>setCreating(true)}>+ Create Tournament</button></section>:<section className="grid">{items.map(t=><article className="card tournament" key={t.id}><div><h2>{t.name}</h2><p className="stats"><b>{t.dayCount}</b> days <span>·</span> <b>{t.gameCount}</b> games <span>·</span> <b>{t.umpireCount}</b> umpires</p><p>Last updated: {fmtDate(t.updated_at)}</p></div><a className="open" href={`/tournament/${t.id}`}>Open Tournament →</a></article>)}</section>}
 <style jsx>{`main{min-height:100vh;background:#f5f7f8;color:#1c2b33;font-family:Arial,sans-serif;padding-bottom:60px}header{background:#fff;border-bottom:1px solid #dde5e9;padding:30px 6%}.brand{font-size:11px;letter-spacing:2px;color:#5d7380}h1{margin:6px 0;font-size:32px}h2{margin:0 0 8px}p{color:#6d7e86;font-size:13px}.toolbar{padding:22px 6% 0}.grid{display:grid;gap:16px;padding:22px 6%}.card{background:#fff;border:1px solid #dce4e8;border-radius:10px;padding:22px}.tournament{display:flex;justify-content:space-between;align-items:center;gap:20px}.stats{font-size:14px;color:#334951}.stats span{margin:0 5px;color:#9aa8ae}.open{display:inline-block;background:#1587b2;color:#fff;text-decoration:none;border-radius:6px;padding:10px 14px;font-weight:700;font-size:13px;white-space:nowrap}.primary{background:#1587b2;color:#fff;border:1px solid #1587b2;border-radius:6px;padding:10px 14px;font-weight:700;cursor:pointer}.empty{margin:22px 6%;text-align:center;padding:60px 20px}.loading{text-align:center;padding:60px;color:#6d7e86}.error{margin:22px 6%;padding:14px;background:#fff1ef;border:1px solid #e4b9b3;border-radius:8px}.error button{margin-left:12px}form{display:flex;gap:10px;align-items:center}input{flex:1;padding:11px;border:1px solid #cbd6dc;border-radius:6px;font:inherit}form button{border:1px solid #cbd6dc;background:#fff;border-radius:6px;padding:10px 14px;cursor:pointer}@media(max-width:600px){.tournament{display:block}.open{margin-top:15px}form{flex-direction:column;align-items:stretch}}`}</style></main>
}
